### ISSUE TITLE
Add nft.storage provider

### ISSUE THREAD

**Issue by ChaituVR** [snapshot-labs/pineapple#99]
https://nft.storage/ is from protocol labs (the same team behind ipfs and filecoin)

**Comment by bonustrack** [comment]
Isnt the same than web3 storage?

**Comment by ChaituVR** [comment]
Oops! didn't realize they both are the same 😄 
![image](https://user-images.githubusercontent.com/15967809/188837234-25644e1c-ef8a-4e13-bef3-5668b247ccb8.png)
